"""users table

Revision ID: 37b831303d25
Revises: 899a63e898a1
Create Date: 2024-02-16 23:44:41.863504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37b831303d25'
down_revision: Union[str, None] = '899a63e898a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('portfolio', sa.Column('name', sa.String(), nullable=False))
    op.add_column('portfolio', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('portfolio', sa.Column('coins', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('portfolio', sa.Column('amount', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('portfolio', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('portfolio', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'portfolio', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolio', type_='foreignkey')
    op.drop_column('portfolio', 'owner_id')
    op.drop_column('portfolio', 'created_at')
    op.drop_column('portfolio', 'amount')
    op.drop_column('portfolio', 'coins')
    op.drop_column('portfolio', 'price')
    op.drop_column('portfolio', 'name')
    op.drop_table('users')
    # ### end Alembic commands ###
