"""coins column added

Revision ID: 899a63e898a1
Revises: 58681978e885
Create Date: 2024-02-07 04:23:23.040972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899a63e898a1'
down_revision: Union[str, None] = '58681978e885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('coins', sa.Float(), server_default='0.0', nullable=False))
    op.alter_column('portfolio', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('portfolio', 'coins')
    # ### end Alembic commands ###
